#!/bin/bash
<<'end_long_comment'
Copyright 2017 Luis J. Centeno - luisjcenteno@live.com

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
end_long_comment

regex='(https?|ftp|file|http)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

#Check if the given parameter is a valid URL
if [[ $1 =~ $regex ]]; then
    echo "-------------------------------------------------"
    wget -O ~/temp_pkg.deb $1 && sudo dpkg -i ~/temp_pkg.deb
    echo "-------------------------------------------------"
    echo "DONE"
    rm ~/temp_pkg.deb

#If the given parameter is I show usage info
elif [ "$1" == "i" ]; then
    echo "  $(tput setaf 2)Use this simple script to automatically download a .deb file from a url and install it."
    echo " $(tput setaf 3)Example: $(tput setaf 4)'addi https://webserver/file.deb'"

#if the given parameter is empty show a description of the script
elif [[ -z "$1" ]]; then
    echo "  $(tput setaf 2)Automatic DEB downloader & installer"
    echo " ------------------------------------------------------"
    echo "  $(tput setaf 2)Type the url to *.deb file, followed by [ENTER]"
    echo "  $(tput setaf 2)or type 'i' for information of script usage"

#Finally if the parameter given not pass any validation show a message to user
else
    echo "  $(tput setaf 1)The given package url isn't valid'"
fi